import oracledb


def get_connection():
    return oracledb.connect(
        user="nuray",
        password="12345",
        dsn="localhost/ORCL1"
    )


# cursor = conn.cursor() SQL sorgularini icra etmek ucun "cursor" yaradir.
# Cursor SQL - i Oracle serverine gonderir ve neticeleri oturur.
def create_tables():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
    BEGIN 
       EXECUTE IMMEDIATE 'CREATE TABLE users (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY,
          username VARCHAR2(50) UNIQUE,
          password VARCHAR2(50),
          PRIMARY KEY (id)
    )';
    EXCEPTION 
    WHEN OTHERS THEN 
    IF SQLCODE != -955 THEN 
         RAISE;
       END IF;

    END;
    """)
    cursor.execute(""""
    BEGIN 
      EXECUTE IMMEDIATE 'CREATE TABLE courses (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY, 
      name VARCHAR2(100),
      description VARCHAR2(200),
      PRIMARY KEY (id)
     )';
    EXCEPTION 
       WHEN OTHERS THEN(
       IF SQQLCODE != -995 THEN 
            RAISE;
        END IF;
    END;
    """)
    cursor.execute(""""
    BEGIN 
       EXECUTE IMMEDIATE 'CREATE TABLE user_courses (
         user_id NUMBER,
         course_id NUMBER ,
         PRIMARY KEY (user_id, course_id)
        );
    EXCEPTION 
       WHEN OTHERS THEN 
          IF SQLCODE != -995 THEN 
             RAISE;
          END IF;
    END;
    """)
    conn.commit()
    cursor.close()
    conn.close()


